# Generated by Django 5.0.3 on 2026-01-25 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_id_column', models.CharField(help_text='Column name that contains the product identifier', max_length=100)),
                ('stock_column', models.CharField(help_text='Column name that contains stock quantities', max_length=100)),
                ('price_column', models.CharField(blank=True, help_text='Column name that contains price (optional)', max_length=100, null=True)),
                ('current_file', models.FileField(blank=True, null=True, upload_to='supplier_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
